version: "3.7"
services:
    dashboard-backend:
        container_name: therivervan/raspberrydashboardbackend
        image: therivervan/raspberrydashboardbackend
        build:
            context: RaspberryDashboard-Backend\
            dockerfile: Dockerfile
        ports:
            - "5000:80"
            - "5001:443"
    dashboard-frontend:
        container_name: therivervan/raspberrydashboardfrontend
        image: therivervan/raspberrydashboardfrontend
        build: 
            context: RaspberryDashboard-Frontend\
            dockerfile: Dockerfile
        ports:
            - "80:80"