version: "3.7"
services:
    dashboard-backend:
        container_name: therivervan-raspberrydashboardbackend
        image: therivervan/raspberrydashboardbackend
        environment:
                - DiscordBotToken=placeholder
                - AllowOrgin=192.168.178.52:5001
                - ASPNETCORE_HTTPS_PORT=5001
                - ASPNETCORE_URLS=https://+;http://+ mywebapi
                - Kestrel__Certificates__Default__Path=/app/cert-aspnetcore.pfx
                - Kestrel__Certificates__Default__Password=ufo
        build:
            context: RaspberryDashboard-Backend/
            dockerfile: Dockerfile.amd64
        ports:
            - "5000:80"
            - "5001:443"
    dashboard-frontend:
        container_name: therivervan-raspberrydashboardfrontend
        image: therivervan/raspberrydashboardfrontend
        environment:
                - baseURL=https://192.168.178.52:5001
        build: 
            context: RaspberryDashboard-Frontend/
            dockerfile: Dockerfile.amd64
        ports:
            - "80:80"